apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-config
  namespace: default
data:
  index.js: |
    const express = require('express');
    const app = express();

    app.get('/', (req, res) => {
      res.send('Hello, ArgoCD!');
    });

    const PORT = process.env.PORT || 3000;
    app.listen(PORT, () => {
      console.log(`Server is running on port ${PORT}`);
    });
  package.json: |
    {
      "name": "argocd-example",
      "version": "1.0.0",
      "main": "index.js",
      "scripts": {
        "start": "node index.js"
      },
      "dependencies": {
        "express": "^4.18.2"
      }
    }
