apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nodejs
  labels:
    app: argocd-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-nodejs
  template:
    metadata:
      labels:
        app: argocd-nodejs
    spec:
      containers:
        - name: argocd-nodejs
          image: cardosojorge65/argocd-nodejs-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
