apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-nodejs
  template:
    metadata:
      labels:
        app: argocd-nodejs
    spec:
      containers:
      - name: nodejs-app
        image: node:14
        command: ["npm", "start"]
        workingDir: /app
        volumeMounts:
        - name: app-volume
          mountPath: /app
      volumes:
      - name: app-volume
        emptyDir: {}
