apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nodejs
  labels:
    app: argocd-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-nodejs
  template:
    metadata:
      labels:
        app: argocd-nodejs
    spec:
      containers:
        - name: argocd-nodejs
          image: cardosojorge65/argocd-nodejs-app:latest
          ports:
            - containerPort: 3000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: APP_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nodejs-config
                  key: DB_PASSWORD
