apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-nodejs
  template:
    metadata:
      labels:
        app: argocd-nodejs
    spec:
      containers:
      - name: argocd-nodejs
        image: argocd-nodejs-app:latest
        ports:
        - containerPort: 3000