apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  username: YWRtaW4=  # Base64 de "admin"
  password: c2VjdXJlcGFzc3dvcmQ=  # Base64 de "securepassword"
