apiVersion: v1
kind: Service
metadata:
  name: argocd-nodejs-service
  namespace: default
spec:
  selector:
    app: argocd-nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
